spring:
  rabbitmq:
    host: 192.168.57.131
    port: 5672
    username: guest
    password: guest
    virtual-host: / #配置每个用户的序列主机
    listener:
      simple:
        prefetch: 1 #表示每次只获取一条消息，消费完后再拉取下一条